// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkincareTracker.API.Data;

#nullable disable

namespace SkincareTracker.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260611181241_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SkincareTracker.API.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConflictsWith")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConflictsWith = "AHA,BHA,Vitamin C",
                            Name = "Retinol",
                            Notes = "Use at night only. Avoid with acids."
                        },
                        new
                        {
                            Id = 2,
                            ConflictsWith = "Retinol,Niacinamide",
                            Name = "Vitamin C",
                            Notes = "Best used in AM. Unstable with some actives."
                        },
                        new
                        {
                            Id = 3,
                            ConflictsWith = "Vitamin C",
                            Name = "Niacinamide",
                            Notes = "Great for pores and brightening."
                        },
                        new
                        {
                            Id = 4,
                            ConflictsWith = "Retinol,BHA",
                            Name = "AHA",
                            Notes = "Exfoliant. Do not layer with retinol."
                        },
                        new
                        {
                            Id = 5,
                            ConflictsWith = "Retinol,AHA",
                            Name = "BHA",
                            Notes = "Salicylic acid family. Unclogs pores."
                        },
                        new
                        {
                            Id = 6,
                            ConflictsWith = "",
                            Name = "Hyaluronic Acid",
                            Notes = "Safe to combine with most actives."
                        },
                        new
                        {
                            Id = 7,
                            ConflictsWith = "",
                            Name = "SPF",
                            Notes = "Always last step in AM routine."
                        },
                        new
                        {
                            Id = 8,
                            ConflictsWith = "AHA,BHA",
                            Name = "Peptides",
                            Notes = "Broken down by acids."
                        });
                });

            modelBuilder.Entity("SkincareTracker.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SkincareTracker.API.Models.ProductIngredient", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.HasKey("ProductId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("ProductIngredients");
                });

            modelBuilder.Entity("SkincareTracker.API.Models.Routine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DaysOfWeek")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimeOfDay")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Routines");
                });

            modelBuilder.Entity("SkincareTracker.API.Models.RoutineProduct", b =>
                {
                    b.Property<int>("RoutineId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer");

                    b.HasKey("RoutineId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("RoutineProducts");
                });

            modelBuilder.Entity("SkincareTracker.API.Models.SkinLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hydration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Oiliness")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductsUsed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sensitivity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SkinConditionScore")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SkinLogs");
                });

            modelBuilder.Entity("SkincareTracker.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkinConcerns")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkinType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SkincareTracker.API.Models.ProductIngredient", b =>
                {
                    b.HasOne("SkincareTracker.API.Models.Ingredient", "Ingredient")
                        .WithMany("ProductIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkincareTracker.API.Models.Product", "Product")
                        .WithMany("ProductIngredients")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SkincareTracker.API.Models.Routine", b =>
                {
                    b.HasOne("SkincareTracker.API.Models.User", "User")
                        .WithMany("Routines")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkincareTracker.API.Models.RoutineProduct", b =>
                {
                    b.HasOne("SkincareTracker.API.Models.Product", "Product")
                        .WithMany("RoutineProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkincareTracker.API.Models.Routine", "Routine")
                        .WithMany("RoutineProducts")
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Routine");
                });

            modelBuilder.Entity("SkincareTracker.API.Models.SkinLog", b =>
                {
                    b.HasOne("SkincareTracker.API.Models.User", "User")
                        .WithMany("SkinLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkincareTracker.API.Models.Ingredient", b =>
                {
                    b.Navigation("ProductIngredients");
                });

            modelBuilder.Entity("SkincareTracker.API.Models.Product", b =>
                {
                    b.Navigation("ProductIngredients");

                    b.Navigation("RoutineProducts");
                });

            modelBuilder.Entity("SkincareTracker.API.Models.Routine", b =>
                {
                    b.Navigation("RoutineProducts");
                });

            modelBuilder.Entity("SkincareTracker.API.Models.User", b =>
                {
                    b.Navigation("Routines");

                    b.Navigation("SkinLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
